[i]
url = "https://youtu.be/2kEJoWfobpA?si=nhUSHr1dV3Y9VTdd"

[o.aggressive-dogfooding-and-reputation-to-your-peers]
start = "5:09"
end = ""

[o.the-grep-man-page-was-20-lines-you-could-actually-read-it]
start = "6:45"
end = ""

[o.assets-vs-liabilities-if-you-touched-the-source-of-a-program-you-owned-it]
start = "11:05"
end = ""

[o.make-and-extremely-short-man-pages-as-the-interface-for-sharing-code]
start = "11:40"
end = ""

[o.rewrote-the-shell-bc-ken-thompson-was-in-berkeley-for-a-year-and-he-owned-the-original-shell]
start = "13:30"
end = ""
