[i]
url = "https://youtu.be/MkJkyMuBm3g?si=WNDMYcgRrni-R6Gs"

[o.quit-being-maintainer-of-busybox-when-bureaucracy-made-it-not-fun-anymore]
start = "11:28"
end = "?"

[o.the-cheyenne-mountain-story-and-simplicity]
start = "12:14"
end = "?"

[o.reading-gnu-cat]
start = "13:00"
end = "?"