[i]
url = "https://youtu.be/Sg4U4r_AgJU?si=820YuBOrehAIgog2"

[o.speed-of-poc-increases-orders-of-magnitude-by-separating-exploration-from-production]
start = "0:00"
end = ""

[o.tower-of-babel]
start = "5:50"
end = ""

[o.larry-walls-definition-of-scripting-languages-includes-text-as-a-basic-data-type]
start = "12:16"
end = ""

[o.alan-perlis-epigrams-on-programming-worth-getting]
start = "19:45"
end = ""

[o.there-are-things-that-you-think-should-be-one-line-of-code-how-do-you-design-a-language-so-that-they-are-one-line-of-code]
start = "20:37"
end = ""