[i]
url = "https://youtu.be/MShbP3OpASA?si=V18T84VSp1Etg6nX"

[o.forced-to-dogfood-his-own-tools]
start = "5:04"
end = "7:46"

[o.decided-he-wanted-unix]
start = "6:14"
end = "7:46"

[o.built-what-he-wanted-and-then-others-started-selling-it]
start = "7:47"
end = "9:48"

[o.build-what-you-wish-existed]
start = "9:05"
end = "9:48"

[o.passion-for-computing-but-didnt-know-what-an-assembler-was]
start = "10:25"
end = "11:38"

[o.open-source-is-powerful-because-its-bottom-up-long]
start = "11:38"
end = "15:34"

[o.open-source-is-powerful-because-its-bottom-up-short]
start = "14:31"
end = "15:34"

[o.human-nature-as-process-and-web-of-trust]
start = "16:40"
end = "18:18"

[o.human-nature-as-process-it-works-bc-didnt-enforce-top-down-hierarchy-but-used-bottom-up-hierarchy]
start = "18:02"
end = "18:18"

[o.c-and-filesystem-paths-and-microoptimization-for-his-own-personal-use]
start = "20:42"
end = "23:42"

[o.wrote-linux-because-he-wanted-to-use-it-on-his-personal-machines]
start = "23:45"
end = "27:10"

[o.never-had-to-deal-with-a-single-business-related-thing-ever]
start = "27:16"
end = "28:01"

[o.in-bottom-up-bdfl-systems-there-is-no-bus-problem]
start = "32:12"
end = "35:09"

[o.the-suicidal-developer-came-from-linus-being-nice]
start = "35:11"
end = "37:59"

[o.linus-on-the-great-minds-who-made-unix]
start = "38:00"
end = "38:52"

[o.on-being-an-anti-visionary]
start = "55:15"
end = "57:30"

[o.vision-vs-passion]
start = "57:15"
end = "57:30"

[o.startups-and-open-source]
start = "59:30"
end = "1:00:28"