[i]
url = "https://youtu.be/WVTWCPoUt8w?si=S8DHeOlp8a_AysmR"

[o.realized-what-he-wanted-was-unix-on-his-personal-machine]
start = "14:33"
end = "15:20"

[o.realizes-hes-going-to-write-an-operating-system-and-first-release-took-less-than-three-months]
start = "19:46"
end = "20:37"